### PR TITLE
add sample app url to repo

### PR DESCRIPTION
**Pull request by nidhimj22**
Added Sample app to the README.

### CODE REVIEW

**Comment by nidhimj22** [comment]
I signed it!

**Comment by Dignifiedquire** [comment]
Thanks, can you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) please?

**Comment by nidhimj22** [comment]
@Dignifiedquire  Changed commit message.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
