### PR TITLE
Use the official local nodejs package.

### PR DESCRIPTION
**Pull request by Varun-garg**

### CODE REVIEW

**Comment by Varun-garg** [comment]
I signed it!

**Comment by Pringels** [comment]
This merge broke all our tests :( Can you please provide some context as to why this pull request was necessary?

**Comment by Varun-garg** [comment]
Hey @Pringels I just ran samples in [this](https://github.com/browserstack/karma-browserstack-example) repo after upgrading the version and tests seemed to have run fine. We upgraded this repo because there were some cases where `browserstacktunnel-wrapper` was not able to properly download the BrowserStack Local binaries. Could you provide the logs so we can debug further?

**Comment by Pringels** [comment]
@Varun-garg the log simply indicates that Browserstack was unable to connect to our CI agents. (connection refused) I didn't spend much time investigating as I had an urgent release, so I just rolled back to 1.4. I will investigate further next week and get back to you.

**Comment by csvn** [comment]
@Pringels I think your CI broke due to either #155 or #156. I'm planning a PR to fix both as soon as I can.

Ping @Varun-garg

**Pull request merged**
