### PR TITLE
Update all dev dependencies (greenkeeper rollup)

### PR DESCRIPTION
**Pull request by krotscheck**
This patch rolls up all the patches from greenkeeper into one single
commit. It also includes an update to grunt required by grunt-auto-release's
peerDependencies.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
It seems travis is unhappy. Could you check that please?

**Comment by krotscheck** [comment]
Roger wilco.

**Comment by krotscheck** [comment]
Hrm. One of the deep transient dependencies (`git-remote-origin-url`), updated to use ES2015 syntax in version 2.0.0. Before I dig into unwinding that dependency chain, is there a real need to continue supporting node 0.12 and 0.10? Given that both of them are EOL'd by the node foundation (https://github.com/nodejs/LTS), and 4 & 6 are the only two that are actively supported, the effort to manually manage the dependency chain (and likely necessary shrinkwrapping) may not be worth it.

If it is... alright, we can do that, but then greenkeeper's not going to be a useful tool for this repository, as we're going to hit more and more ES2015 syntax in the near future that'll prevent us from updating dependencies.

**Comment by dignifiedquire** [comment]
thanks, did another run of updates on master

**Pull request closed without merging**
