### PR TITLE
chore: Drop io.js, test on Node.js 4.x

### PR DESCRIPTION
**Pull request by mzgol**

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Please do a rebase, I had to force push some fixes, because I screwed up some release process stuff

**Comment by mzgol** [comment]
Rebased.

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by mzgol** [comment]
I've also switched to the new container infrastructure on Travis.

**Comment by mzgol** [comment]
Oh, too late. ;)

**Comment by Dignifiedquire** [comment]
It got in, by seconds :dart:

**Pull request merged**
