### PR TITLE
Adding more env options for Drone as well as general CI systems.

### PR DESCRIPTION
**Pull request by jackspirou**
For parity with https://github.com/karma-runner/karma-sauce-launcher/pull/83.

### CODE REVIEW

**Comment by jackspirou** [comment]
cc @bradrydzewski

**Comment by jackspirou** [comment]
@karma-runner/karma-browserstack-launcher any thoughts?

**Comment by Dignifiedquire** [comment]
What's the reason for adding these? In which environment are they used? Where do these names come from?

**Comment by jackspirou** [comment]
@Dignifiedquire checkout http://readme.drone.io/usage/variables/

Specifically one of these are for Drone the Open Source CI/CD system which runs tests and more in Docker containers.  More here: https://github.com/drone/drone.

Drone also mentions env vars for compatibility with other CI systems, so I believe they would be a good integration for the karma-runner plugins that launch other testing services.  Enhancing your CI/CD compatibility beyond Travis and CircleCI is probably a good idea for more adoption.

This same change has been merged https://github.com/karma-runner/karma-testingbot-launcher/pull/3 and https://github.com/karma-runner/karma-sauce-launcher.

```
Environment

Drone injects the following namespaced environment variables into every build:

DRONE=true
DRONE_REPO - repository name for the current build
DRONE_BRANCH - branch name for the current build
DRONE_COMMIT - git sha for the current build
DRONE_DIR - working directory for the current build
DRONE_BUILD_NUMBER - build number for the current build
DRONE_PULL_REQUEST - pull request number fo the current build
DRONE_JOB_NUMBER - job number for the current build
DRONE_TAG - tag name for the current build

Drone also injects CI_ prefixed variables for compatibility with other systems:

CI=true
CI_NAME=drone
CI_REPO - repository name of the current build
CI_BRANCH - branch name for the current build
CI_COMMIT - git sha for the current build
CI_BUILD_NUMBER - build number for the current build
CI_PULL_REQUEST - pull request number fo the current build
CI_JOB_NUMBER - job number for the current build
CI_BUILD_DIR - working directory for the current build
CI_BUILD_URL - url for the current build
CI_TAG - tag name for the current build
```

**Comment by Dignifiedquire** [comment]
Thanks @jackspirou that sounds reasonable, would be good to add some details about this to the respective readmes so people actually know that these variables are used.

**Comment by jackspirou** [comment]
@Dignifiedquire the other karma-runner launchers I submitted this PR too already had some `README.md` documentation on their env vars, and I submitted updates to them as well.  There is currently no documentation about the existing env vars for this project. I can add something brief to this project's `README.md` if that would help.

**Comment by Dignifiedquire** [comment]
@jackspirou that would be great yes

**Comment by jackspirou** [comment]
@dignifiedquire brief `README.md` explanation added, and git commits squashed.

**Comment by dignifiedquire** [comment]
Thanks :octocat:

**Pull request merged**
