### PR TITLE
Added support for using BrowserStackReporter with a proxy

### LINKED ISSUE #85: ERROR [reporter.browserlabs]: ? Could not update BrowserStack status
### Expected behaviour
there should be no error

### Actual behaviour
`12 12 2016 19:42:15.160:ERROR [reporter.browserlabs]: ? Could not update BrowserStack status`

### Environment Details

- Karma version: 1.3.0
- karma-browserstack-launcher version: 1.1.1
- using proxy to connect the browserstack server, has already set proxyHost, proxyPort in karma.conf.js

### Steps to reproduce the behaviour

after run karma start karma.conf.js

### PR DESCRIPTION
**Pull request by atti187**
Fixes #85

### CODE REVIEW

**Comment by 4garfield** [comment]
It's useful while trying to update the browserstack report behind proxy.

**Comment by Eddman** [comment]
Is it going to be merged? It was opened on March 17th and approved on April 4th...it is issue for many of BS users....

**Comment by JakeChampion** [comment]
It was approved by someone who is not a maintainer of this repository.

**Comment by Eddman** [comment]
Could you please also publish new version into NPM registry? Thanks.

**Pull request merged**
